# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hastaliste.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(481, 428)
        self.hastaTable = QtWidgets.QTableWidget(Form)
        self.hastaTable.setGeometry(QtCore.QRect(10, 60, 461, 351))
        self.hastaTable.setObjectName("hastaTable")
        self.hastaTable.setColumnCount(4)
        self.hastaTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.hastaTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hastaTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hastaTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hastaTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hastaTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hastaTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hastaTable.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 20, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hastalar"))
        item = self.hastaTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "TC"))
        item = self.hastaTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ad"))
        item = self.hastaTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Soyad"))
        item = self.hastaTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Telefon"))
        self.label.setText(_translate("Form", "Hasta Listesi"))
