# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'randevuTablo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(603, 453)
        self.randevuTablo = QtWidgets.QTableWidget(Form)
        self.randevuTablo.setGeometry(QtCore.QRect(0, 0, 601, 391))
        self.randevuTablo.setObjectName("randevuTablo")
        self.randevuTablo.setColumnCount(6)
        self.randevuTablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.randevuTablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevuTablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevuTablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevuTablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevuTablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevuTablo.setHorizontalHeaderItem(5, item)
        self.iptalButon = QtWidgets.QPushButton(Form)
        self.iptalButon.setGeometry(QtCore.QRect(230, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.iptalButon.setFont(font)
        self.iptalButon.setObjectName("iptalButon")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.randevuTablo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Hasta"))
        item = self.randevuTablo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Hastane"))
        item = self.randevuTablo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Bölüm"))
        item = self.randevuTablo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Doktor"))
        item = self.randevuTablo.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tarih"))
        item = self.randevuTablo.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Saat"))
        self.iptalButon.setText(_translate("Form", "İptal Et"))
